build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Wyoming Piper Normalize"
  org.opencontainers.image.description: "Wyoming protocol server for the Piper text-to-speech system, featuring Russian text normalization via RUNorm"
  org.opencontainers.image.source: "https://github.com/wirgen/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  WPN_VERSION: 1.0.0